# home.kv
<Home>:
    name: 'home'
    MDScreen:
        MDLabel:
            text: "Home"
            theme_text_color: "Custom"
            text_color: "white"
            font_style: "H3"
            halign: "center"
            pos_hint: {"center_y": .95}
        MDFillRoundFlatIconButton:
            icon: "language-python"
            text: "Question Screen"
            pos_hint: {"center_x": .5, "center_y": .15}
            on_release: root.btn_question()