# home.kv
<Home>:
    name: 'home'
    MDScreen:
        MDLabel:
            text: "Home"
            theme_text_color: "Custom"
            text_color: "black"
            font_style: "H3"
            halign: "center"
        MDFillRoundFlatIconButton:
            icon: "language-python"
            text: "Question Screen"
            pos_hint: {"center_x": .5, "center_y": .15}
            on_release: app.change_screen('question')