<Screen1>:
    name: 'screen1'
    MDLabel:
        id: screen1_label
        text: 'Screen1'
        font_size: 18
        halign: 'center'

    ScrollView:
        BoxLayout:
            orientation: 'vertical'
            id: card_container

    MDRaisedButton:
        icon: "arrow-right-bold"
        text: 'Screen2'
        font_size: 18
        pos_hint: {'center_x':0.5,'center_y':0.1}
        on_press: root.manager.current = 'screen2'   